### ISSUE TITLE
[Bug] Seasons poster cannot load

### ISSUE THREAD

**Issue by nyouness** [JagandeepBrar/lunasea#764] opened 2023-08-25 23:10 UTC
**Describe the Bug**
 Add a new serie to sonarr or jellyseerr or reiverr through LunaSea. The seasons poster cannot load.

**To Reproduce**
The seasons poster cannot load even after restarting app / clearing the cache / disabling the profile and enabling again.

**Expected Behaviour**
The seasons poster should display.

**Screenshots**
![Screenshot 2023-08-25 235208](https://github.com/JagandeepBrar/lunasea/assets/117232906/064633cc-d7a1-45fc-9545-2a1db8146891)
![Screenshot 2023-08-25 235046](https://github.com/JagandeepBrar/lunasea/assets/117232906/dec24866-7088-473e-8486-e016fae212c4).

**Versions**
LunaSea 10.2.5 windows
Sonarr 4.0.0.646 .

**Additional context**
The cover and poster loads fine .

**Comment by JagandeepBrar** [comment] 2023-08-27 22:22
Are you using Sonarr v4? It appears that they have removed the property which contained the remote image URL from the seasons payload, which means that season posters may not be possible with Sonarr v4.

I am validating with the development team and if confirmed I will be removing the image placeholder from the season list.

**Comment by nyouness** [comment] 2023-08-27 22:30
yep im using Sonarr v4 , ah okay thats the case , is there a way to get posters from like TMDB or TVDb instead of relaying on sonarr ? and ty for replaying!

**Comment by JagandeepBrar** [comment] 2023-08-28 09:51
Sadly this isn't possible as I am not eligible for free access to TheTVDB's API and Sonarr does not store/use TheMovieDB IDs under the hood.

Sadly if the Sonarr team has removed season posters from the payload then they will need to be removed.

**Comment by JagandeepBrar** [comment] 2023-08-28 15:53
As it turns out this is a new bug introduced in Sonarr v4 and the team has been notified.

https://github.com/Sonarr/Sonarr/issues/5971

Once the above issue has been fixed and released, LunaSea should start to load season images again. I'll keep this issue open for tracking purposes however.

**Comment by JagandeepBrar** [comment] 2023-08-30 02:58
This issue has been fixed in #767 alongside the upstream changes in Sonarr.

Please update your Sonarr installation and the fix on the LunaSea-side will be deployed soon as well!

**Closed by JagandeepBrar** 2023-08-30 02:58 UTC
Labels: bug, upstream:package
